### PR TITLE
[15.0][mig]-purchase_comment_template

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
@ForgeFlow

### CODE REVIEW

**Review by HviorForgeFlow — CHANGES_REQUESTED** [review]
Functional review: I was able to generate a PO with comments on top and bottom

Is it possible to default models when accessing from the Purchase  > Configuration > Document Comments to "purchase.order"
I understand the code and I could know what to put there, maybe a help could be useful and/or a placeholder

image

After creating 2 comments I couldn't see them on tree view, maybe a filter is not configured properly:
image

**Comment by JuanyDForgeflow** [comment]
@HviorForgeFlow please review again

**Review by AaronHForgeFlow — APPROVED** [review]
Functional LG

**Review by HviorForgeFlow — APPROVED** [review]

**Pull request merged**
