### PR TITLE
[14.0][MIG] migration of module purchase_incoming_products

### PR DESCRIPTION
**Pull request by alan196**
### Proposed changes

I've migrated the module purchase_incoming_products and its functionalities from Odoo 13.0 to 14.0. I've checked if all unit tests are still running.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Migration Update

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

### CODE REVIEW

**Comment by igallart** [comment]
@alan196 , this PR is good? What is the problem?

**Comment by alan196** [comment]
@igallart  module works, it only needs review to be merged

**Comment by igallart** [comment]
@pedrobaeza , who is responsible for approving this?

**Comment by pedrobaeza** [comment]
It follows standard OCA guidelines, needing 2 reviews and one for the PSC.

Please remove plurals in the module name.

**Comment by alan196** [comment]
@pedrobaeza the name of the module was changed 👍

**Review by pedrobaeza — APPROVED** [review]
Code review

**Review by dreispt — APPROVED** [review]

**Pull request merged**
