### PR TITLE
[16.0][ADD] purchase_report_payment_term

### PR DESCRIPTION
**Pull request by rinaldifirdaus**
This module adds Payment Term notes to the Purchase Order & Request for Quotation report.

@qrtl

### CODE REVIEW

**Review by yostashiro — APPROVED** [review]
LGTM.
image

**Review by AungKoKoLin1997 — APPROVED** [review]
LGTM

**Review by rvalyi — APPROVED** [review]

**Comment by AungKoKoLin1997** [comment]
@purchase-workflow-maintainers
Can we get this PR merged?

**Review by HviorForgeFlow — APPROVED** [review]

**Pull request merged**
