### PR TITLE
[16.0][MIG] purchase_comment_template: Migration to 16.0

### PR DESCRIPTION
**Pull request by SirAionTech**
Migration from `15.0` (https://github.com/OCA/purchase-reporting/tree/697f28a199eeab2aae34af7a1c67b36f268739d9/purchase_comment_template).

I also added:

- a little improvement for creating comments from the purchase order form;
- a fix for the comments menu;

both in their own commit so they can be back-ported if needed.

### CODE REVIEW

**Comment by SirAionTech** [comment]
@MiquelRForgeFlow @AaronHForgeFlow @alan196 you worked on this, would you like to have a look?

**Comment by AaronHForgeFlow** [comment]
Is there a reason you started from the 14.0 version instead the 15.0?

**Comment by SirAionTech** [comment]
> Is there a reason you started from the 14.0 version instead the 15.0?

I didn't really see it! :open_mouth: thanks for pointing that out, let me do it again starting from that one.
I just supposed it hadn't been migrated yet because https://github.com/OCA/purchase-reporting/pull/50 is still open, I just didn't check the `15.0` branch.

**Comment by SirAionTech** [comment]
@AaronHForgeFlow now it migrates the `15.0` module

**Review by GasparJarsa — APPROVED** [review]
Functional review. It looks good for me.

**Review by alan196 — APPROVED** [review]
Technical and functional review 👍 LGTM

**Pull request merged**
