### PR TITLE
7 fix 1331394

### PR DESCRIPTION
**Pull request by eLBati**
Moved from https://code.launchpad.net/~agilebg/purchase-report/7_fix_1331394/+merge/223799
It fixes https://bugs.launchpad.net/purchase-report/+bug/1331394

### CODE REVIEW

**Comment by sebastienbeau** [comment]
:+1: tested.
Table header are really better, thanks for the fix.
Regarding the failed on Travis, the travis file is ok on ocb branch, it's not your fault

**Comment by max3903** [comment]
:-1: 
It fails on OCB and Odoo. base_headers_webkit module is missing. Can you add his repo in Travis ?

**Comment by sebastienbeau** [comment]
Oups sorry I forget a word "Travis file is NOT OK on ocb" (I should say on oca main branch) intead even the master fail to build.
By the way we should fix the Travis file. As suggest by Max you can add the missing dependency ( or proposing a new pr fort fixing it).
Thanks

**Comment by eLBati** [comment]
Now the base_headers_webkit module is installed.
For the rules error, I opened https://github.com/OCA/purchase-reporting/issues/4

**Comment by eLBati** [comment]
Same as https://github.com/OCA/account-invoice-reporting/pull/2

**Comment by eLBati** [comment]
Red because of https://github.com/OCA/purchase-reporting/pull/7

**Comment by bwrsandman** [comment]
#7 was merged
Build restarted
LGTM :+1:

**Comment by foutoucour** [comment]
:+1:

**Comment by gdgellatly** [comment]
Hi,

I reviewed and I'm sure it fixes the bug, but I noticed another bug in code review.  Purchase Price is a v6.1 Decimal Accuracy, in v7 it should be Product Price and Account respectively.

``` python
'price_unit': fields.float('Unit Price', required=True, digits_compute= dp.get_precision('Product Price')),
        'price_subtotal': fields.function(_amount_line, string='Subtotal', digits_compute= dp.get_precision('Account')),
```

Do we want to fix it here or do you want me to wait for merge and make a seperate PR?

**Comment by bwrsandman** [comment]
@gdgellatly If it fixes the bug in question, we can merge.

For another bug, please create another issue or PR.

An exception would be if the bug fix creates a new bug.

**Pull request merged**
