### PR TITLE
[ADD] 9.0 - Added purchase order report module

### PR DESCRIPTION
**Pull request by SerpentCS**
This module is converted to qweb from webkit

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check errors in runbot/Travis

**Comment by serpentcs-dev1** [comment]
@pedrobaeza @jbeficent @aheficent
test_server.py is showing "DataError : value too long for type character varying(128)" 
I guess it is regarding author given in openerp file exceeds the characters. What would be the solution to this?
and same for other PR : https://github.com/OCA/purchase-reporting/pull/15

**Comment by pedrobaeza** [comment]
I'm afraid there's no solution for now: https://github.com/odoo/odoo/issues/5850, only to shorten the length.

**Comment by AaronHForgeFlow** [comment]
The limit is too short. Is it possible to set the authors in a different key?

**Comment by pedrobaeza** [comment]
No, not possible. You should shorten your names to `Eficent` and `Serpent CS`, and let the full legal name to the README.

**Comment by serpentcs-dev1** [comment]
Okay, thanks @pedrobaeza @aheficent for the efforts & quick reply.

**Pull request closed without merging**
